### ISSUE TITLE
Can't provision vagrant VM

### ISSUE THREAD

**Issue by honza** [pculture/amara-metrics#2]
I can't seem to be able to provision the box.  Here is the error output:

```
~/Code/amara-metrics [master] $ vagrant destroy --force && vagrant up
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
[default] Importing base box 'lucid32'...
[default] The guest additions on this VM do not match the install version of
VirtualBox! This may cause things such as forwarded ports, shared
folders, and more to not work properly. If any of those things fail on
this machine, please update the guest additions and repackage the
box.

Guest Additions Version: 4.1.0
VirtualBox Version: 4.1.18
[default] Matching MAC address for NAT networking...
[default] Clearing any previously set forwarded ports...
[default] Fixed port collision for 22 => 2222. Now on port 2200.
[default] Forwarding ports...
[default] -- 22 => 2223 (adapter 1)
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Running any VM customizations...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
[default] Setting host name...
[default] Mounting shared folders...
[default] -- v-root: /vagrant
[default] -- metrics: /opt/metrics
[default] -- manifests: /tmp/vagrant-puppet/manifests
[default] -- v-pp-m0: /tmp/vagrant-puppet/modules-0
[default] Running provisioner: Vagrant::Provisioners::Puppet...
[default] Running Puppet with /tmp/vagrant-puppet/manifests/vagrant.pp...
stdin: is not a tty
Could not parse options: invalid option: --node_name_value

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cd /tmp/vagrant-puppet/manifests && puppet apply --verbose --node_name_value
vagrant --modulepath '/tmp/vagrant-puppet/modules-0'
/tmp/vagrant-puppet/manifests/vagrant.pp
```

**Comment by ehazlett** [comment]
What version of Vagrant are you using?

**Comment by honza** [comment]
`1.0.2`

**Comment by unisubs-transifex** [comment]
I just tested with 1.0.3 and it's provisioning.  It looks like 1.0.2 is
using a rather old version of puppet.

Evan

**Comment by honza** [comment]
Tested on `1.0.3` and I get the same error.

**Comment by ehazlett** [comment]
Did you destroy the VM first?

**Comment by honza** [comment]
Yep. I always do `$ vagrant destroy --force && vagrant up` when trying to get stuff to work.

**Comment by unisubs-transifex** [comment]
I just did a complete rebuild (re-clone repo, re-create VM, boot) and it
works.

Can you give me the md5 of ~/.vagrant.d/boxes/lucid32/box-disk1.vmdk ?

Evan

**Comment by honza** [comment]
Here `007c0cff988608761160eae646d3f0f6`.

**Comment by honza** [comment]
I figured it out. The `--node_name_value` option was introduced somewhere after `2.5.1` (what the base box has installed) and  `2.7.18` (latest).

Running, `sudo gem install puppet` and then `vagrant provision` works great.

**Comment by unisubs-transifex** [comment]
Ah I believe this is because of the base box.  That is a problem (IMO) with
the vagrant base boxes.  I re-downloaded both the lucid and precise base
boxes about a month ago which gives me Puppet 2.7.14.  You can use your fix
or upgrade the base box.

Evan

**Comment by honza** [comment]
I did try it with a Precise box and it worked great. I didn't realize that existing base boxes got upgraded. Downloading right away. Thanks

**Comment by ehazlett** [comment]
Yeah they really should version the boxes.  Let me know if you still have issues.

**Comment by ponasohan** [comment]
I am using vagrant 1.6.3

When i run the vagrent, (eg Vagrant up)

==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default: augeas-lenses libaugeas0 libxml2 libxml2-dev
==> default: Suggested packages:
==> default: augeas-doc
==> default: The following NEW packages will be installed:
==> default: augeas-lenses augeas-tools libaugeas-dev libaugeas0 libxml2-dev
==> default: The following packages will be upgraded:
==> default: libxml2
==> default: 1 upgraded, 5 newly installed, 0 to remove and 130 not upgraded.
==> default: Need to get 1,859 kB of archives.
==> default: After this operation, 4,121 kB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libxml2 amd64 2.7.8.dfsg-5.1ubuntu4.11 [674 kB]
==> default: Get:2 http://us.archive.ubuntu.com/ubuntu/ precise/main augeas-lenses all 0.10.0-0ubuntu4 [175 kB]
==> default: Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/main libaugeas0 amd64 0.10.0-0ubuntu4 [171 kB]
==> default: Get:4 http://us.archive.ubuntu.com/ubuntu/ precise/main augeas-tools amd64 0.10.0-0ubuntu4 [22.1 kB]
==> default: Get:5 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libxml2-dev amd64 2.7.8.dfsg-5.1ubuntu4.11 [805 kB]
==> default: Get:6 http://us.archive.ubuntu.com/ubuntu/ precise/main libaugeas-dev amd64 0.10.0-0ubuntu4 [11.1 kB]
==> default: Fetched 1,859 kB in 13s (139 kB/s)
==> default: (Reading database ...
==> default: 64685 files and directories currently installed.)
==> default: Preparing to replace libxml2 2.7.8.dfsg-5.1ubuntu4.4 (using .../libxml2_2.7.8.dfsg-5.1ubuntu4.11_amd64.deb) ...
==> default: Unpacking replacement libxml2 ...
==> default: Selecting previously unselected package augeas-lenses.
==> default: Unpacking augeas-lenses (from .../augeas-lenses_0.10.0-0ubuntu4_all.deb) ...
==> default: Selecting previously unselected package libaugeas0.
==> default: Unpacking libaugeas0 (from .../libaugeas0_0.10.0-0ubuntu4_amd64.deb) ...
==> default: Selecting previously unselected package augeas-tools.
==> default: Unpacking augeas-tools (from .../augeas-tools_0.10.0-0ubuntu4_amd64.deb) ...
==> default: Selecting previously unselected package libxml2-dev.
==> default: Unpacking libxml2-dev (from .../libxml2-dev_2.7.8.dfsg-5.1ubuntu4.11_amd64.deb) ...
==> default: Selecting previously unselected package libaugeas-dev.
==> default: Unpacking libaugeas-dev (from .../libaugeas-dev_0.10.0-0ubuntu4_amd64.deb) ...
==> default: Processing triggers for man-db ...
==> default: Setting up libxml2 (2.7.8.dfsg-5.1ubuntu4.11) ...
==> default: Setting up augeas-lenses (0.10.0-0ubuntu4) ...
==> default: Setting up libaugeas0 (0.10.0-0ubuntu4) ...
==> default: Setting up augeas-tools (0.10.0-0ubuntu4) ...
==> default: Setting up libxml2-dev (2.7.8.dfsg-5.1ubuntu4.11) ...
==> default: Setting up libaugeas-dev (0.10.0-0ubuntu4) ...
==> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: Installing Puppet requirements
==> default: /tmp/vagrant-shell: line 54: /usr/bin/gem: No such file or directory
==> default: Finished installing Puppet requirements
==> default: Installing Puppet 3.4.3
==> default: /tmp/vagrant-shell: line 58: /usr/bin/gem: No such file or directory
==> default: Finished installing Puppet 3.4.3
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: stdin: is not a tty
==> default: Error: Could not parse application options: invalid option: --parser
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

FACTER_ssh_username='vagrant' FACTER_provisioner_type='virtualbox' FACTER_vm_target_key='vagrantfile-local' puppet apply --verbose --hiera_config /vagrant/puphpet/puppet/hiera.yaml --parser future --modulepath '/tmp/vagrant-puppet-3/modules-0:/etc/puppet/modules' --manifestdir /tmp/vagrant-puppet-3/manifests --detailed-exitcodes /tmp/vagrant-puppet-3/manifests/site.pp

Stdout from the command:

Stderr from the command:

stdin: is not a tty
Error: Could not parse application options: invalid option: --parser

Please let me know any solution.
